CREATE DATABASE SHIPMENTS
GO
USE SHIPMENTS

CREATE TABLE SHIPMENT(
ORDER_ID INT IDENTITY(1,1),---PRIMARY KEY OR UNIQUE ENSURE EVERY DATA IS UNIQUE TO AVOID ANY STUPID DUPLICATES
---FOREIGN KEY CONCEPT ----
---THE WORD KEY MEANS COLUMN
REQUESTED_DELIVERY_DATE DATE,
SHIPPING_DATE DATE
)
SELECT * FROM SHIPMENT
GO
---COMPARE THE REQUESTED DELIVERY DATE WITH THE SHIP DATE IN DAYS AND RETURN IF THE ORDER IS ON_TIME OR LATE


INSERT INTO SHIPMENT VALUES('2016-01-03', '2016-01-03')
INSERT INTO SHIPMENT VALUES('2016-01-04', '2016-01-03')
INSERT INTO SHIPMENT VALUES('2016-01-04', '2016-01-05')
INSERT INTO SHIPMENT VALUES('2016-01-05', '2016-01-03')
---FORMAT (TIMELINE,'D','eN-US') AS Date is like excel custom formattimg e.g format(2016-01-05, 'D','eN-US') D means Days

--task: NOW let's query the data to see if most of our deliveries were late or on-time based using datediff(day, start_date, end_date)
SELECT * FROM SHIPMENT
GO
SELECT
ORDER_ID,
FORMAT(REQUESTED_DELIVERY_DATE,'D','en-US') As REQUESTED_DATE,
FORMAT(SHIPPING_DATE,'D','en-US') AS SHIPPING_DATE,
DATEDIFF(DAY,REQUESTED_DELIVERY_DATE,SHIPPING_DATE) AS NO_OF_DAYS_TAKEN_TO_DELIVER_EACH_PRODUCT_TO_CUSTOMERS,
CASE
WHEN DATEDIFF(DAY, REQUESTED_DELIVERY_DATE, SHIPPING_DATE) >
0
THEN 'LATE'
ELSE 'ONTIME'
END DELIVERY_STATUS ---AS NEW DELIVERY_STATUS COLUMN
FROM SHIPMENT
WHERE SHIPPING_DATE IS NOT NULL
ORDER BY
REQUESTED_DELIVERY_DATE DESC;