create database LEAD_VS_LAG
GO
USE LEAD_VS_LAG
DROP TABLE MTN_EMPLOYEES
---Oya let"s create a small table called MTN_EMPLOYEES
CREATE TABLE MTN_EMPLOYEES(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
GENDER NVARCHAR(10),
SALARY INT
)
INSERT INTO MTN_EMPLOYEES VALUES (1,'MARK','MALE',1000)
INSERT INTO MTN_EMPLOYEES VALUES (2,'JOHN','MALE',2000)
INSERT INTO MTN_EMPLOYEES VALUES (3,'PAM','FEMALE',3000)
INSERT INTO MTN_EMPLOYEES VALUES (4,'SARA','FEMALE',4000)
INSERT INTO MTN_EMPLOYEES VALUES (5,'TODD','MALE',5000)
INSERT INTO MTN_EMPLOYEES VALUES (6,'MARY','FEMALE',6000)
INSERT INTO MTN_EMPLOYEES VALUES (7,'BEN','MALE',7000)
INSERT INTO MTN_EMPLOYEES VALUES (8,'JODI','FEMALE',8000)
INSERT INTO MTN_EMPLOYEES VALUES (9,'TOM','MALE',9000)
INSERT INTO MTN_EMPLOYEES VALUES (10,'RON','MALE',9500)
GO
SELECT DISTINCT GENDER, NAME FROM MTN_EMPLOYEES
GO
SELECT * FROM MTN_EMPLOYEES ---IN EXCEL IS = UNIQUE(TABLE[COLUMN])
--COUNT THE STATISTICS OF GENDER BELOW
SELECT COUNT(DISTINCT GENDER) AS NO_OF_GENDER FROM MTN_EMPLOYEES
GO
SELECT COUNT(DISTINCT NAME) AS NO_OF_PEOPLE FROM MTN_EMPLOYEES

---LEAD AND LAG FUNCTIONS EXAMPLES WITHOUT PARTITIONS: THIS EXAMPLE LEADS 2 ROWS AND LAGS 1 ROW FROM THE CURRENT ROW.
---WHEN YOU ARE ON THE FIRST ROW, LEAD(SALARY,2,-1) ALLOWS YOU TO MOVE FOWARD 2 ROWS AND RETRIEVE THE SALARY FROM THE THIRD ROW
---WHEN YOU ARE ON THE FIRST ROW LAG(SALARY, 1, -1) ALLOWS YOU TO MOVE BACKWARD 1 ROW. SINCE THERE ARE NO ROWS BEYOND ROW 1, LAG FN IN THIS CASE RETURNS THE DEFAULT VALUE -1
--WHEN YOU ARE ON THE LAST ROW, LEAD(SALARY,2, -1) ALLOWS YOU TO MOVE FOWARD 2 ROWS. SINCE THERE IS NO ROWS BEYOND THE LAST ROW 1, LEAD FN IN THIS CASE RETURNS THE DEFAULT VALUE -1

---WHEN YOU ARE ON THE LAST ROW, LAG(SALARY. 1. -1) ALLOWS US TO BACKWARD 1 ROW AND RETRIEVE THE SALARY FROM THE PREVIOUS ROW.
GO
SELECT NAME, GENDER, SALARY,
LEAD(SALARY, 2,-1) OVER (ORDER BY SALARY) AS LEAD_2,
LAG(SALARY, 1, -1) OVER (ORDER BY SALARY) AS LAG_1
FROM MTN_EMPLOYEES
---HOW LEAD FUNCTION WORKS
SELECT NAME, GENDER, SALARY,
LEAD(SALARY,2, 0) OVER (ORDER BY SALARY) AS LEAD_2 FROM MTN_EMPLOYEES
GO
---HOW LAG FUNCTION WORKS
LAG(SALARY, 1, 0) OVER (ORDER BY SALARY) AD LAG_1
FROM MTN_EMPLOYEES

